name: Android CI

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Gradle Wrapper Cache
        uses: actions/cache@v2
        id: gradle-wrapper-cache
        with:
          path: ~/.gradle/wrapper/
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-wrapper-
      - name: Gradle Cache
        uses: actions/cache@v2
        id: gradle-cache
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('buildSrc/src/main/kotlin/Dependencies.kt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-
      - run: .github/scripts/gradlew_recursive.sh androidDependencies
        if: steps.gradle-wrapper-cache.outputs.cache-hit != 'true' || steps.gradle-cache.outputs.cache-hit != 'true'
      - name: Build and Test
        run: .github/scripts/gradlew_recursive.sh clean assemble test
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Upload Test Reports
        uses: actions/upload-artifact@v2
        with:
          path: app/build/reports/tests/
